### ISSUE TITLE
[Bug] Installation bug

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/sublime-backrefs#2]
### Summary

I can not install sublime-backrefs.
### Expected behavior

Successful installing sublime-backrefs.
### Actual behavior

``` shell
C:\WINDOWS\system32>pip install backrefs
Collecting backrefs
  Downloading backrefs-1.0.post1.tar.gz (40kB)
    100% |################################| 40kB 266kB/s
    Complete output from command python setup.py egg_info:
    Downloading: http://www.unicode.org/Public/8.0.0/ucd/UnicodeData.txt --> C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\tools\unicodedata\8.0.0\UnicodeData.txt
    Downloading: http://www.unicode.org/Public/8.0.0/ucd/Scripts.txt --> C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\tools\unicodedata\8.0.0\Scripts.txt
    Downloading: http://www.unicode.org/Public/8.0.0/ucd/Blocks.txt --> C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\tools\unicodedata\8.0.0\Blocks.txt
    Downloading: http://www.unicode.org/Public/8.0.0/ucd/PropList.txt --> C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\tools\unicodedata\8.0.0\PropList.txt
    Traceback (most recent call last):
      File "e:\python35-32\lib\urllib\request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "e:\python35-32\lib\http\client.py", line 1106, in request
        self._send_request(method, url, body, headers)
      File "e:\python35-32\lib\http\client.py", line 1151, in _send_request
        self.endheaders(body)
      File "e:\python35-32\lib\http\client.py", line 1102, in endheaders
        self._send_output(message_body)
      File "e:\python35-32\lib\http\client.py", line 934, in _send_output
        self.send(msg)
      File "e:\python35-32\lib\http\client.py", line 877, in send
        self.connect()
      File "e:\python35-32\lib\http\client.py", line 849, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "e:\python35-32\lib\socket.py", line 711, in create_connection
        raise err
      File "e:\python35-32\lib\socket.py", line 702, in create_connection
        sock.connect(sa)
    TimeoutError: [WinError 10060] ╧юя√Єър єёЄрэютшЄ№ ёюхфшэхэшх с√ыр схчєёях°эющ, Є.ъ. юЄ фЁєуюую ъюья№■ЄхЁр чр ЄЁхсєхьюх тЁхь  эх яюыєўхэ эєцэ√щ юЄъышъ, шыш с√ыю ЁрчюЁтрэю єцх єёЄрэютыхээюх ёюхфшэхэшх шч-чр эхтхЁэюую юЄъышър єцх яюфъы■ўхээюую ъюья№■ЄхЁр

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\setup.py", line 43, in download_unicodedata
        unidatadownload.download_unicodedata(unicodedata.unidata_version)
      File "C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\tools\unidatadownload.py", line 54, in download_unicodedata
        response = urlopen(furl)
      File "e:\python35-32\lib\urllib\request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "e:\python35-32\lib\urllib\request.py", line 466, in open
        response = self._open(req, data)
      File "e:\python35-32\lib\urllib\request.py", line 484, in _open
        '_open', req)
      File "e:\python35-32\lib\urllib\request.py", line 444, in _call_chain
        result = func(*args)
      File "e:\python35-32\lib\urllib\request.py", line 1282, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "e:\python35-32\lib\urllib\request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [WinError 10060] ╧юя√Єър єёЄрэютшЄ№ ёюхфшэхэшх с√ыр схчєёях°эющ, Є.ъ. юЄ фЁєуюую ъюья№■ЄхЁр чр ЄЁхсєхьюх тЁхь  эх яюыєўхэ эєцэ√щ юЄъышъ, шыш с√ыю ЁрчюЁтрэю єцх єёЄрэютыхээюх ёюхфшэхэшх шч-чр эхтхЁэюую юЄъышър єцх яюфъы■ўхээюую ъюья№■ЄхЁр>

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\setup.py", line 77, in <module>
        download_unicodedata()
      File "C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\setup.py", line 50, in download_unicodedata
        assert not fail, "Failed to download unicodedata!"
    AssertionError: Failed to download unicodedata!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\3809~1\AppData\Local\Temp\pip-build-6062f5m1\backrefs\

C:\WINDOWS\system32>
```
### Steps to reproduce

I open my command prompt and I run command `pip install backrefs`
### Environment

**Operating system and version:**
Windows 10.0.14393
**Python:**
3.5.2
**Pip:**
pip 8.1.2 from e:\python35-32\lib\site-packages\pip-8.1.2-py3.5.egg (python 3.5)

Thanks.

**Comment by facelessuser** [comment]
Can you move this issue here? https://github.com/facelessuser/backrefs.  sublime-backrefs is a special repo so Sublime can pull this for plugins like BracketHighlighter and RegReplace.  backrefs is the actual repo distributed by pip.

I'll have to translate the error into english later today.  It is possible one of the dependencies has changed, or the unicodedata I used to download moved.  Not sure as I haven't yet decoded the data.  I will rerun the continuous validation checks later and see.  I do test Python3.5, so I don't think it is that.

**Comment by Kristinita** [comment]
OK, I can move issue.

But I'm hardly going to use backrefs. I just tried to have experiment set backefs. Since I got the bug, I wrote to you.

Default Sublime Text engine not supported [POSIX](https://libraries.io/github/facelessuser/sublime-backrefs#posix-style-properties-1) and I search in Google, how I can use POSIX for search and replace in Sublime Text. You know, how use POSIX for search and replace in Sublime Text?

Thanks.

**Comment by facelessuser** [comment]
Besides having a new need to explicitly ignore the `.tox` folder when linting, I see no problems in continuous integration in py2.7, py3.3, py3.4, py3.5: https://travis-ci.org/facelessuser/backrefs.

Unfortunately, I have no idea what this says:

```
TimeoutError: [WinError 10060] ╧юя√Єър єёЄрэютшЄ№ ёюхфшэхэшх с√ыр схчєёях°эющ, Є.ъ. юЄ фЁєуюую ъюья№■ЄхЁр чр ЄЁхсєхьюх тЁхь  эх яюыєўхэ эєцэ√щ юЄъышъ, шыш с√ыю ЁрчюЁтрэю єцх єёЄрэютыхээюх ёюхфшэхэшх шч-чр эхтхЁэюую юЄъышър єцх яюфъы■ўхээюую ъюья№■ЄхЁр
```

> Default Sublime Text engine not supported POSIX and I search in Google, how I can use POSIX for search and replace in Sublime Text. You know, how use POSIX for search and replace in Sublime Text?

Do you mean via the find and replace panel? I think Sublime uses boost regex: http://www.boost.org/doc/libs/1_56_0/libs/regex/doc/html/boost_regex/syntax/basic_extended.html.  So stuff like that should work `[[:lower:]]+` or `\p{lower}` etc.  Now I don't know if the character classes match the posix variants or not.

As for backrefs and Sublime, if you have `BracketHighlighter` or `RegReplace` installed, backrefs should be available from Sublime command line.  The character classes in `sublime-backrefs` are pre-compiled for Sublime's Python.  It was mainly written to be used by plugins (much like how both BracketHighlighter and RegReplace utilize it).  If you wish to use backrefs in Sublime, then you can tap into it via a plugin, but it will not be accessible in the find and replace panel.

As for what is available via the Sublime Text find and replace panel, I would read up on the regex engine.  See the Sublime Text Unofficial Documentation for links to boost regex documentation.

If you are able to give me a translated error from what you are getting, maybe I can debug your backrefs install issue, but from all my testing, it installs fine.  I don't know if it is a regional issue, or something like that, but without more info, I will have a hard time debugging this.

**Comment by facelessuser** [comment]
What is clear is that your install is having a hard time downloading the unicode data files that backrefs uses to create database of unicode classes for the unicode back references.  Unfortunately I don't know why it is failing on your system.

**Comment by facelessuser** [comment]
I looked up WinError 10060, and I found this http://stackoverflow.com/a/16312067.  Maybe you need to look at your network settings.

**Comment by facelessuser** [comment]
Looking at the original issue more, and looking over the log, I see that some of the files downloaded fine.  I am curious how many attempts you tired to install, just one?  If you tried multiple times, does it always fail at the same point?  I wonder if you were just having network issues on one particular file and it failed.

**Comment by Kristinita** [comment]
> Do you mean via the find and replace panel? I think Sublime uses boost regex: http://www.boost.org/doc/libs/1_56_0/libs/regex/doc/html/boost_regex/syntax/basic_extended.html. So stuff like that should work `[[:lower:]]+` or `\p{lower}` etc. Now I don't know if the character classes match the posix variants or not.

Thank you!

> Looking at the original issue more, and looking over the log, I see that some of the files downloaded fine. I am curious how many attempts you tired to install, just one? If you tried multiple times, does it always fail at the same point? I wonder if you were just having network issues on one particular file and it failed.

I install backrefs today, I get good result:

``` shell
C:\WINDOWS\system32>pip install backrefs
Collecting backrefs
  Using cached backrefs-1.0.post1.tar.gz
Installing collected packages: backrefs
  Running setup.py install for backrefs ... done
Successfully installed backrefs-1.0.post1
```

Thanks.

**Comment by facelessuser** [comment]
> I install backrefs today, I get good result:

Cool, glad it worked.
