### ISSUE TITLE
This package isn't present in Package Control

### ISSUE THREAD

**Issue by starkatt85** [facelessuser/sublime-backrefs#5]
I'm setting my Sublime Text in my newly install Linux Distro.

I wanted to install LSP and other lsp-<name> packages. While I pressed enter to install LSP its didn't do anything.
I opened the terminal and saw:
``` shell
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'backrefs' is not currently installed; installing...
Package Control: The dependency 'backrefs' is not available
Package Control: The dependency 'backrefs' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages
```

So I though it would be a problem in Dependency and explicitly searched for "backrefs" in Package Control Panel. It wasn't there. Also I checked packagecontrol.io and it wasn't there too.

I don't know what to do, I tried installing backrefs with regex support using pip (hoping that a random thing makes the job done) but didn't do the trick.

I'm also new to bits like this: backrefs and the working of Package Control, etc.

I think the problem is backrefs isn't available in the repository. Please take a look and please let me if it was a mistake on your side or other's, If its other's mistake I will go there and ask for help.

Thank You
Rero

**Comment by facelessuser** [comment]
@rerorengine, this is not an issue with Sublime backrefs, but an issue with Package Control. You can see that we are specified in Package Control's dependency list: https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json#L49.

See Package Control issue here: https://github.com/wbond/package_control/issues/1581. The problem must be fixed upstream, not here.
